/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-11-24 14:00:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<style>\r\n");
      out.write("#birthday{width:60px;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <h1>[회원가입]</h1>\r\n");
      out.write("   <table border=1 >\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>사진</td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <img src=\"http://placehold.it/150x120\" id=\"image\" width=150>\r\n");
      out.write("               <input type=\"file\" name=\"file\">\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td width=60>아이디</td>\r\n");
      out.write("            <td width=650><input type=\"text\" name=\"id\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>비밀번호</td>\r\n");
      out.write("            <td><input type=\"password\" name=\"pw\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>이메일</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"email\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>성별</td>\r\n");
      out.write("            <td>\r\n");
      out.write("               남:<input type=\"radio\" name=\"gender\" value=\"m\">\r\n");
      out.write("               여:<input type=\"radio\" name=\"gender\" value=\"f\">\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>관심 키워드</td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <select name=\"keyword\">\r\n");
      out.write("                  <option value=\"게임\">게임</option>\r\n");
      out.write("                  <option value=\"운동\">운동</option>\r\n");
      out.write("                  <option value=\"낚시\">낚시</option>\r\n");
      out.write("                  <option value=\"자동차\">자동차</option>\r\n");
      out.write("               </select>\r\n");
      out.write("               <select name=\"keyword\">\r\n");
      out.write("                  <option value=\"게임\">게임</option>\r\n");
      out.write("                  <option value=\"운동\">운동</option>\r\n");
      out.write("                  <option value=\"낚시\">낚시</option>\r\n");
      out.write("                  <option value=\"자동차\">자동차</option>\r\n");
      out.write("               </select>\r\n");
      out.write("               <select name=\"keyword\">\r\n");
      out.write("                  <option value=\"게임\">게임</option>\r\n");
      out.write("                  <option value=\"운동\">운동</option>\r\n");
      out.write("                  <option value=\"낚시\">낚시</option>\r\n");
      out.write("                  <option value=\"자동차\">자동차</option>\r\n");
      out.write("               </select>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>이름</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"name\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>생년월일</td>\r\n");
      out.write("            <td>\r\n");
      out.write("               ");

int year = 2018; //년도
int[] daysOfMonth = {0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31}; // 12월까지 일 갯수. 0월은 없다
int dayOfWeek = 2; // 해당 주 중에 몇 번째 칸인지 저장,  2018년 1월은 월요일부터 시작하므로 2 입력;
for(int month = 1; month <= 12; month++){
    
      out.write("\r\n");
      out.write("    <p>");
      out.print(year );
      out.write('년');
      out.write(' ');
      out.print(month );
      out.write("월</p>\r\n");
      out.write("    <div id=\"calendar-content\">일</div>\r\n");
      out.write("    <div id=\"calendar-content\">월</div>\r\n");
      out.write("    <div id=\"calendar-content\">화</div>\r\n");
      out.write("    <div id=\"calendar-content\">수</div>\r\n");
      out.write("    <div id=\"calendar-content\">목</div>\r\n");
      out.write("    <div id=\"calendar-content\">금</div>\r\n");
      out.write("    <div id=\"calendar-content\">토</div>\r\n");
      out.write("    <br id=\"calendar-enter\" />\r\n");
      out.write("    ");

     
    for (int blankDay = 1; blankDay < dayOfWeek; blankDay++) {
        // 여기는 띄워야할 칸을 작성하는 구간입니다.
        // firstDayOfWeek 이 첫날의 요일을 제시(일:1 월:2 ... 토:7)하므로
        //그 전까지만 채워야 한다
        
      out.write("<div id=\"calendar-content\"> </div>");

    }
 
    int daysPerMonth = daysOfMonth[month]; // 해당 월의 일 수
    for (int day = 1; day <= daysPerMonth; day++) {
        
      out.write("<div id=\"calendar-content\">");
      out.print(day);
      out.write("</div>");

        if (dayOfWeek >= 7) {
            
      out.write("<br id=\"calendar-enter\" />");

            dayOfWeek = 1;
        } else {
            dayOfWeek++;
        }
    }
    
      out.write("<br id=\"calendar-enter\" /><br />");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("출처: https://msm8994.tistory.com/26 [MSM8994의 화룡점정 블로그]\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>전화번호</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"phone\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>주소</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"addr\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>상세주소</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"addrditail\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td colspan=2>\r\n");
      out.write("               <input type=\"submit\" value=\"가입\">\r\n");
      out.write("               <a href=\"/login\"><input type=\"reset\" value=\"취소\"></a>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
