/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-11-25 02:18:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<style>\r\n");
      out.write("#birthday{width:60px;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <h1>[회원가입]</h1>\r\n");
      out.write("   <form name =\"frm\" action=\"insert\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("   <table border=1 >\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>사진</td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <img src=\"http://placehold.it/150x120\" id=\"image\" width=150>\r\n");
      out.write("               <input type=\"file\" name=\"file\">\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td width=60>아이디</td>\r\n");
      out.write("            <td width=650><input type=\"text\" name=\"id\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>비밀번호</td>\r\n");
      out.write("            <td><input type=\"password\" name=\"pw\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>이메일</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"email\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>성별</td>\r\n");
      out.write("            <td>\r\n");
      out.write("               남:<input type=\"radio\" name=\"gender\" value=\"m\">\r\n");
      out.write("               여:<input type=\"radio\" name=\"gender\" value=\"f\">\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>관심 키워드</td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <select name=\"keyword1\">\r\n");
      out.write("                  <option value=\"게임\">게임</option>\r\n");
      out.write("                  <option value=\"운동\">운동</option>\r\n");
      out.write("                  <option value=\"낚시\">낚시</option>\r\n");
      out.write("                  <option value=\"자동차\">자동차</option>\r\n");
      out.write("               </select>\r\n");
      out.write("               <select name=\"keyword2\">\r\n");
      out.write("                  <option value=\"게임\">게임</option>\r\n");
      out.write("                  <option value=\"운동\">운동</option>\r\n");
      out.write("                  <option value=\"낚시\">낚시</option>\r\n");
      out.write("                  <option value=\"자동차\">자동차</option>\r\n");
      out.write("               </select>\r\n");
      out.write("               <select name=\"keyword3\">\r\n");
      out.write("                  <option value=\"게임\">게임</option>\r\n");
      out.write("                  <option value=\"운동\">운동</option>\r\n");
      out.write("                  <option value=\"낚시\">낚시</option>\r\n");
      out.write("                  <option value=\"자동차\">자동차</option>\r\n");
      out.write("               </select>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>이름</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"name\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>생년월일</td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <input type=\"text\" name=\"birthday\" maxlength=\"6\">:주민번호 앞자리       \r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>전화번호</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"phone\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>주소</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"addr\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>상세주소</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"addrditail\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td colspan=2>\r\n");
      out.write("               <input type=\"submit\" value=\"가입\">\r\n");
      out.write("               <a href=\"/login\"><input type=\"reset\" value=\"취소\"></a>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("     </form> \r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(frm.file).hide();\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#image\").on(\"click\",function(){\r\n");
      out.write("\t\t$(frm.file).click();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(frm.file).on(\"change\",function(){\r\n");
      out.write("\t\tvar file=$(frm.file)[0].files[0];\r\n");
      out.write("\t\t$(\"#image\").attr(\"src\",URL.createObjectURL(file));\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
