/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-11-23 11:09:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class local_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>지역검색</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <h1>[지역검색]</h1>\r\n");
      out.write("   <div id=\"divSearch\">\r\n");
      out.write("      <button id=\"btnSave\">선택저장</button>\r\n");
      out.write("      <input id=\"query\" value=\"버거킹\"> <input type=\"button\"\r\n");
      out.write("         value=\" 검색 \" id=\"btnSearch\"> <span id=\"total\"></span>\r\n");
      out.write("   </div>\r\n");
      out.write("   <table id=\"tbl\" border=1></table>\r\n");
      out.write("   <script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("         <tr class=\"title\">\r\n");
      out.write("         <td width=20><input type=\"checkbox\" id=\"chkAll\"></td>\r\n");
      out.write("         <td width=150>장소명</td>\r\n");
      out.write("         <td width=150>전화번호</td>\r\n");
      out.write("         <td width=300>주소</td>         \r\n");
      out.write("      </tr>\r\n");
      out.write("      {{#each documents}}\r\n");
      out.write("      <tr class=\"row\">\r\n");
      out.write("         <td><input type=\"checkbox\" class=\"chk\" id={{id}} place_name=\"{{place_name}}\" address_name=\"{{address_name}}\" phone=\"{{phone}}\" x={{x}} y={{y}}></td>\r\n");
      out.write("         <td>{{place_name}}</td>\r\n");
      out.write("         <td>{{phone}}</td>\r\n");
      out.write("         <td>{{address_name}}</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      {{/each}}\r\n");
      out.write("      </script>\r\n");
      out.write("   <div id=\"pagination\">\r\n");
      out.write("      <button id=\"btnPre\">이전</button>\r\n");
      out.write("      <button id=\"btnNext\">다음</button>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("   getList();\r\n");
      out.write("   var page = 1;\r\n");
      out.write("\r\n");
      out.write("   $(\"#btnSave\").on(\"click\", function() {\r\n");
      out.write("      if (!confirm(\"선택한 내용을 저장하실래요?\"))\r\n");
      out.write("         return;\r\n");
      out.write("      $(\"#tbl .row .chk:checked\").each(function() {\r\n");
      out.write("         var id = $(this).attr(\"id\");\r\n");
      out.write("         var place_name = $(this).attr(\"place_name\");\r\n");
      out.write("         var address_name = $(this).attr(\"address_name\");\r\n");
      out.write("         var phone = $(this).attr(\"phone\");\r\n");
      out.write("         var x = $(this).attr(\"x\");\r\n");
      out.write("         var y = $(this).attr(\"y\");\r\n");
      out.write("         $.ajax({\r\n");
      out.write("            type : \"post\",\r\n");
      out.write("            url : \"insert\",\r\n");
      out.write("            data : {\"id\" : id,\"place_name\" : place_name,\"address_name\" : address_name,\"phone\" : phone,\"x\" : x,\"y\" : y},\r\n");
      out.write("            success : function() {\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("      });\r\n");
      out.write("      $(\"#tbl .row .chk\").each(function() {\r\n");
      out.write("         $(this).prop(\"checked\", false);\r\n");
      out.write("      });\r\n");
      out.write("      $(\"#tbl #chkAll\").prop(\"checked\", false);\r\n");
      out.write("      alert(\"저장성공\");\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   $(\"#tbl\").on(\"click\", \"#chkAll\", function() {\r\n");
      out.write("      if ($(this).is(\":checked\")) {\r\n");
      out.write("         $(\"#tbl .row .chk\").each(function() {\r\n");
      out.write("            $(this).prop(\"checked\", true);\r\n");
      out.write("         });\r\n");
      out.write("      } else {\r\n");
      out.write("         $(\"#tbl .row .chk\").each(function() {\r\n");
      out.write("            $(this).prop(\"checked\", false);\r\n");
      out.write("         });\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   //각 행의 체크박스를 클릭한 경우\r\n");
      out.write("   $(\"#tbl\").on(\"click\", \".row .chk\", function() {\r\n");
      out.write("      var isCheck = true\r\n");
      out.write("      $(\"#tbl .row .chk\").each(function() {\r\n");
      out.write("         if (!$(this).is(\":checked\"))\r\n");
      out.write("            isCheck = false\r\n");
      out.write("      });\r\n");
      out.write("      if (isCheck) {\r\n");
      out.write("         $(\"#chkAll\").prop(\"checked\", true);\r\n");
      out.write("      } else {\r\n");
      out.write("         $(\"#chkAll\").prop(\"checked\", false);\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   $(\"#btnNext\").on(\"click\", function() {\r\n");
      out.write("      page++;\r\n");
      out.write("      getList();\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   $(\"#btnPre\").on(\"click\", function() {\r\n");
      out.write("      page--;\r\n");
      out.write("      getList();\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   $(\"#btnSearch\").on(\"click\", function() {\r\n");
      out.write("      getList();\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   $(\"#query\").keydown(function(key) {\r\n");
      out.write("      if (key.keyCode == 13) {\r\n");
      out.write("         getList();\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   function getList() {\r\n");
      out.write("      var query = $(\"#query\").val();\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         type : \"get\",\r\n");
      out.write("         url : \"https://dapi.kakao.com/v2/local/search/keyword.json\",\r\n");
      out.write("         headers : {\r\n");
      out.write("            \"Authorization\" : \"KakaoAK 4c9947b8b0448265ca15036c39a7fa4e\"\r\n");
      out.write("         },\r\n");
      out.write("         data : {\r\n");
      out.write("            \"query\" : query,\r\n");
      out.write("            \"page\" : page,\r\n");
      out.write("            \"size\" : 10\r\n");
      out.write("         },\r\n");
      out.write("         dataType : \"json\",\r\n");
      out.write("         success : function(data) {\r\n");
      out.write("            var temp = Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("            $(\"#tbl\").html(temp(data));\r\n");
      out.write("            var total = data.meta.pageable_count;\r\n");
      out.write("            $(\"#total\").html(total + \" 건\");\r\n");
      out.write("            if (page == 1) {\r\n");
      out.write("               $(\"#btnPre\").attr(\"disabled\", true);\r\n");
      out.write("            } else {\r\n");
      out.write("               $(\"#btnPre\").attr(\"disabled\", false);\r\n");
      out.write("            }\r\n");
      out.write("            if (data.meta.is_end) {\r\n");
      out.write("               $(\"#btnNext\").attr(\"disabled\", true);\r\n");
      out.write("            } else {\r\n");
      out.write("               $(\"#btnNext\").attr(\"disabled\", false);\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
